### PR TITLE
eslint for es6

### PR DESCRIPTION
**Pull request by tanhauhau**
Refactoring code to follow [Airbnb Javascript Style Guide](https://github.com/airbnb/javascript).
It is good to start from small to follow a particular style guide, so that code styles are coherent throughout the repo

### CODE REVIEW

**Comment by vutran** [comment]
+1 for this effort. Consistency will make it easy for everyone to read the same way.

Aside from that note, running `npm run lint` is producing a lot of errors that still needs to be addressed.

**Comment by tanhauhau** [comment]
@vutran sure, more refactoring needed to be done to fix those lint errors, such as `no-console` for `console.log`s occurrence within each modules, etc.

**Comment by jcampbell05** [comment]
@tanhauhau Looking good, there is a merge issue which needs to be addressed first.

**Comment by tanhauhau** [comment]
@jcampbell05 i've updated the PR

**Comment by jcampbell05** [comment]
@tanhauhau Thanks for this! Would you like to be invited to our Slack and added as a member as our organisation.

**Comment by tanhauhau** [comment]
@jcampbell05 sure

**Pull request merged**
