### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by radarhere**

### CODE REVIEW

**Comment by jcampbell05** [comment]
Thanks @radarhere ! Would you like to be a contributor for this Project.

**Comment by radarhere** [comment]
Would I like to be a contributor for this project? In the github sense, I already am, since you've merged in my commit, so I will automatically be listed as a contributor. I'm not sure what you're saying.

**Comment by jcampbell05** [comment]
@radarhere I'm meaning as in adding you to the Organization.  We have a policy of asking anybody who contributes any code to try and grow this project :)

**Comment by radarhere** [comment]
Ah. No thanks. I'm a repeat contributor over at https://github.com/python-pillow/Pillow, and so I will keep my attention focused there.

**Pull request merged**
