### PR TITLE
Added semantic tags, restructured HTML, cleaned up/edited CSS

### PR DESCRIPTION
**Pull request by geoffdavis92**
For #43 

Updated home page from this:

Current home page

to this:

PR home page

There are other style changes to the lower sections, but that's all my screen could grab. [Live demo here](https://geoffdavis.info/Bottr/)

In all, I edited:

* HTML: restructured some components, and added semantic tags were possible. I did this somewhat quickly, so there may be a few other tags that could be used.
* CSS: restructured the SCSS file to have a little more hierarchy. (based of [ITCSS](https://speakerdeck.com/dafed/managing-css-projects-with-itcss?slide=48)) Changed a few sections to be more responsive, and fleshed out/cleaned up other components.

I'll revisit some of the SCSS and HTML later when I have more time to look closely, as I know it can be further cleaned up.

### CODE REVIEW

**Comment by jcampbell05** [comment]
Thanks for this @geoffdavis92  - Would you like an invite to our slack group and to be a member of our org ?

**Comment by geoffdavis92** [comment]
@jcampbell05 that would be great! TBH this is my first OS PR, but I am happy to contribute more to the site.

**Comment by jcampbell05** [comment]
@geoffdavis92  No worries, I would love your help on the site. It's looking amazing !

**Comment by geoffdavis92** [comment]
@jcampbell05 Sorry for the late reply! You can send an invite to gdavis@archermalmo.com

**Pull request merged**
